name: audit

on:
  - push
  - pull_request

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Verify dependencies
      run: make verify

    - name: Build
      run: make build

    - name: Run linter
      run: make lint

    # - name: Install staticcheck
    #   run: go install honnef.co/go/tools/cmd/staticcheck@latest

    # - name: Run staticcheck
    #   run: staticcheck ./...

    # - name: Install golint
    #   run: go install golang.org/x/lint/golint@latest

    # - name: Run golint
    #   run: golint ./...

    - name: Run tests
      run: make test